version: '3.5'

services:
  webserver:
    image: humidorweb 
    container_name: webserver-php
    volumes:
      - ./WebContent:/var/www/html
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      humidornet:
        ipv4_address: 10.3.70.30

networks:
  humidornet:
    external: true